config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # get 'mm_request/index'
  #
  # get 'mm_request/show'
  #
  # get 'mm_process_excel_import/index'
  #
  # get 'mm_process_excel_import/show'
  #
  # get 'long_services/index'
  #
  # get 'long_services/jobs'
  #
  # get 'long_services/assets'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  #
  # get 'generators/index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'mm_assets/pb_bodies'

  get 'mm_assets/music'

  get 'mm_assets/price_vals'

  get 'mm_assets/index'

  get 'mm_assets/show'

  get 'mm_assets/required'

  #
  get 'mm_reports/halaal_stores'

  get 'mm_reports/non_halaal_products'


  resources :berta, only: [:index] do
    get :index, on: :member
  end


get 'imports/destroy_all'
  resources :imports, only: [:index, :new, :create, :destroy] do
    put :process_zip_file, on: :member
    put :process_mp3_file, on: :member
    # get :destroy_all, on: :member
  end

  # get 'mm_requests/new_requests'

  resources :mm_adverts

  resources :mm_requests

  get 'mm_request_jobs/download_job'

  resources :mm_request_jobs

  resources :ls_requests

  root 'berta#index'

end

app/models/mm_advert.rb
# frozen_string_literal: true
class MmAdvert < ActiveRecord::Base
end

app/controllers/mm_adverts_controller.rb
# frozen_string_literal: true
class MmAdvertsController < ApplicationController
  def index
    @requests = Import.where(id: MmAdvert.distinct.pluck(:import_id))
  end

  def create
    StoreCodeRequesterJob.perform_now
    MmRequestJob.where(import_id: params[:id]).update(request_accepted: true)
    @requests = MmRequest.where(import_id: params[:id])
    import_id = @requests.first.import_id
    ProcessAdvertJob.perform_now(@requests)
    @adverts = MmAdvert.where(import_id: import_id)
    @import  =  MmRequestJob.where(import_id: params[:id]).last
    render 'show'
  end

  def show
    @adverts = MmAdvert.where(import_id: params[:id])
    @import  =  MmRequestJob.where(import_id: params[:id]).last
  end
end

app/helpers/mm_adverts_helper.rb
# frozen_string_literal: true
module MmAdvertsHelper

  def pbs_not_available(adverts)
    adverts.where(pb_available: false).to_a.uniq(&:description).size
  end




end

app/views/mm_adverts/index.html.erb
<h4>MeatMarket</h4>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Requested Adverts</h3>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table id="table_starting_fifteen" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
        <thead>
        <tr>
          <th class="text-center" >#</th>
          <th class="text-center" >Request Number</th>
          <th class="text-center" >Import ID</th>
          <th class="text-center" >Import File</th>
          <th class="text-center" >View Request</th>
        </tr>
        </thead>
        <tbody>
        <% count = 0 %>
        <% @adverts.each do |request| %>
            <tr>
              <td class="text-center"  ><%= count += 1 %></td>
              <td class="text-center"><%= count %></td>
              <td class="text-center"><%= request %></td>
              <td class="col-md-2"><%= request.imported_file %></td>
              <td class="text-center"><%=  %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/mm_adverts/show.html.erb
<h5>MeatMarket : Adverts Details</h5>
<div class="panel panel-primary">
  <div class="panel-primary">
    <div class="panel-heading"> ID: <%= @import.import_id %> - <%= @import.job_name.gsub('_', ' ') %></div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table id="table_starting_ten" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
        <thead>
        <tr>
          <th class="text-center" >#</th>
          <th class="text-center" >Import ID</th>
          <th class="text-center" >Description</th>
          <th class="text-center" >Product</th>
          <th class="text-center" >Product Code</th>
          <th class="text-center" >Language</th>
          <th class="text-center" >Lang Code</th>
          <th class="text-center" >Theme</th>
          <th class="text-center" >Theme Code</th>
          <th class="text-center" >Price</th>
          <th class="text-center" >Price Code</th>
          <th class="text-center" >Start Date</th>
          <th class="text-center" >End Date</th>
          <th class="text-center" >Store Listing File</th>
        </tr>
        </thead>
        <tbody>
        <% count = 0 %>
        <% @adverts.sort.each do |advert| %>
            <tr class="<%= row_state(advert.pb_available) %>">
              <td class="text-center"><%= count += 1  %></td>
              <td class="text-center"><%= advert.import_id  %></td>
              <td class="text-left"><%= advert.description %></td>
              <td class="text-left"><%= advert.product %></td>
              <td class="text-center"> <%= advert.item_code %></td>
              <td class="text-center" ><%= advert.lang_full %></td>
              <td class="text-center"><%= advert.lang_code %></td>
              <td class="text-center"><%= advert.theme  %></td>
              <td class="text-center"><%= advert.theme_code %></td>
              <td class="text-center"><%= advert.price.to_s.to_f %></td>
              <td class="text-center"><%= advert.price_code %></td>
              <td class="text-center"><%= advert.start_date %></td>
              <td class="text-center"><%= advert.end_date %></td>
              <td class="col-sm-1"><%= advert.dsf %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <tbody>
        <%
          total_ads = @adverts.to_a.uniq{ |p| p.description }.size
          pbs_not_avail = pbs_not_available(@adverts)
          pbs_not_avail = 1 if pbs_not_avail == 0
        %>
        Total Advert Requests: <%= total_ads %><br>
        PB's Not Available: <%= pbs_not_avail  %><br>
        PB's Not Available: <%= number_to_percentage(pbs_not_avail.to_f / total_ads * 100, precision: 1) %>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <% unless MmRequestJob.where(import_id: @adverts.first.import_id)[0][:advert_requests_accepted] && MmRequestJob.where(import_id: @adverts.first.import_id)[0][:job_requests_accepted]   %>
      <%  MmRequestJob.where(import_id: @adverts.first.import_id).update(advert_requests_accepted: true) %>
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <tbody>
          <td class="text-center"><%= button_to "Cancel",  root_path, method: :get, class: "btn btn-danger"  %></td>
          <td class="text-center"><%= button_to "Accept Adverts", mm_request_jobs_path(id: @adverts.first.import_id, set_id: true), method: :post, class: "btn btn-success", data: { disable_with: "Processing. Please wait..." }  %></td>
          </tr>
          </tbody>
        </table>
      </div>
  <% else %>
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <tbody>
          <tr>
            <td class="text-center"><%= button_to "Back", :back, method: :get, class: "btn btn-success btn-sm"  %></td>
            <td class="text-center"><%= button_to "View Job", mm_request_job_path, method: :get, class: "btn btn-success btn-sm"  %></td>
            <td class="text-center"><%= button_to "Request Jobs", mm_request_jobs_path, method: :get, class: "btn btn-success btn-sm"  %></td>
          </tr>
          </tbody>
        </table>
      </div>
  <% end %>
</div>