config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # get 'mm_request/index'
  #
  # get 'mm_request/show'
  #
  # get 'mm_process_excel_import/index'
  #
  # get 'mm_process_excel_import/show'
  #
  # get 'long_services/index'
  #
  # get 'long_services/jobs'
  #
  # get 'long_services/assets'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  #
  # get 'generators/index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'mm_assets/pb_bodies'

  get 'mm_assets/music'

  get 'mm_assets/price_vals'

  get 'mm_assets/index'

  get 'mm_assets/show'

  get 'mm_assets/required'

  #
  get 'mm_reports/halaal_stores'

  get 'mm_reports/non_halaal_products'


  resources :berta, only: [:index] do
    get :index, on: :member
  end


get 'imports/destroy_all'
  resources :imports, only: [:index, :new, :create, :destroy] do
    put :process_zip_file, on: :member
    put :process_mp3_file, on: :member
    # get :destroy_all, on: :member
  end

  # get 'mm_requests/new_requests'

  resources :mm_adverts

  resources :mm_requests

  get 'mm_request_jobs/download_job'

  resources :mm_request_jobs

  resources :ls_requests

  root 'berta#index'

end

app/models/mm_request_job.rb
# frozen_string_literal: true
class MmRequestJob < ApplicationRecord
end

app/controllers/mm_request_jobs_controller.rb
# frozen_string_literal: true
class MmRequestJobsController < ApplicationController

  def index
    @request_jobs = MmRequestJob.all
    @requests_all = MmRequest.all
    @adverts_all = MmAdvert.all
  end

  def download_job
    job = MmRequestJob.where(id: params[:format]).first
    date = Time.now.strftime('%Y-%m-%d')
    filename = %(#{date}_#{job.id}_#{job.job_name}.zip)
    zip_file = File.join(SPM, job.id.to_s + '.zip' )
    send_file(
        zip_file,
        filename: filename,
        type: "application/zip",
        stream: false
    )
  end

  def create
    MmRequestJob.where(import_id: params[:id]).update(job_requests_accepted: true)
    redirect_to mm_request_jobs_path
  end

  def new
    job_id = params[:format]
    @request_job = MmRequestJob.where(id: job_id)
    import_id =  @request_job[0].import_id

    # AdvertsGeneratorJob.perform_later(adverts, job_id, import_id, current_user.id)
    AdvertsGeneratorJob.perform_now(job_id, import_id, current_user.id)
    flash[:warn] = 'Job completed. The adverts have been generated.'
    redirect_to mm_request_job_path(import_id)
  end

  def show
    @request_job = MmRequestJob.where(import_id: params[:id])
    @adverts = MmAdvert.where(import_id: params[:id]).order('request_id')
    @import  =  MmRequestJob.where(import_id: params[:id]).last
  end

end

app/helpers/mm_request_jobs_helper.rb
# frozen_string_literal: true
module MmRequestJobsHelper

  def process_by_state(job)
    return 'Job Not Accepted!' unless job.job_requests_accepted
    state = job.job_completed ? true : false
    # return button_to('Run Job', { controller: :mm_request_jobs, action: :new, id: job.id }, class: 'btn btn-success btn-xs') unless state

    if job.job_zip_created && state.eql?(true)
      return button_to('Download', mm_request_jobs_download_job_path(job),
                       method: :get, class: 'btn btn-success btn-xs')
    end

    return button_to('Run Job', new_mm_request_job_path(job),
                     method: :get, class: 'btn btn-success btn-xs',
                     data: { disable_with: "Processing. Please wait..." }) unless state
    button_to('Failed', '#',
              class: 'btn btn-danger btn-xs')
  end

end

app/views/mm_request_jobs/index.html.erb
<h4>MeatMarket: Request Jobs</h4>
<div class="panel panel-primary">
  <div class="panel-body">
    <div class="table-responsive">
      <table id="table_starting_fifteen" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
        <thead>
        <tr>
          <th class="text-center" >Job ID</th>
          <th class="text-center" >Import ID</th>
          <th class="text-center" >Job Name</th>
          <th class="text-center" >Start Date</th>
          <th class="text-center" >End Date</th>
          <th class="text-center" >Requests</th>
          <th class="text-center" >Show Requests</th>
          <th class="text-center" >Adverts</th>
          <th class="text-center" >Show Adverts</th>
          <th class="text-center" >Adverts Unavail</th>
          <th class="text-center" >Job Action</th>
          <th class="text-center" >Job Created</th>
          <th class="text-center" >Job Updated</th>
          <th class="text-center" >View Job</th>

        </tr>
        </thead>
        <tbody>
        <% count = 0 %>
        <% def start_date(job)
             return 'empty' if @adverts_all.where(import_id: job.import_id).empty?
               res =  @adverts_all.where(import_id: job.import_id).order('start_date ASC').first.start_date
                return res unless res.nil?
                'oops'
           end

           def end_date(job)
             return 'empty' if @adverts_all.where(import_id: job.import_id).empty?
            res = @adverts_all.where(import_id: job.import_id).order('end_date ASC').last.end_date
             return res unless res.nil?
            'oops'
           end
           def advert_count(job)
             @adverts_all.where(import_id: job.import_id).size
           end
           @request_jobs.sort_by { |m| [m.created_at, m.updated_at].max }.reverse.each do |job| %>
            <tr>
              <td class="text-center"><%= job.id  %></td>
              <td class="text-center"><%= job.import_id  %></td>
              <td class="text-left"><%= job.job_name.split('/').last %></td>
              <td class="text-center"> <%= start_date(job) %></td>
              <td class="text-center" ><%= end_date(job) %></td>
              <td class="text-center"><%= @requests_all.where(import_id: job.import_id).size %></td>
              <td class="text-center"><%= link_to('View', mm_request_path(job.import_id), method: :get, class: 'btn btn-primary btn-xs')  %></td>
              <td class="text-center"><%= advert_count(job) %></td>
              <td class="text-center"><%= link_to('View', mm_advert_path(job.import_id), method: :get, class: 'btn btn-primary btn-xs') unless advert_count(job).eql?(0) %></td>
              <td class="text-center"><%= @adverts_all.where(import_id: job.import_id, pb_available: false).size %></td>
              <td class="text-center"><%= process_by_state(job) %></td>
              <td class="text-center"><%= job.created_at.to_formatted_s(:db)  %></td>
              <td class="text-center"><%= job.updated_at.to_formatted_s(:db)  %></td>
              <td class="text-center"><%= button_to('Show', mm_request_job_path(job.import_id),
                                                    method: :get, class: 'btn btn-primary btn-xs') %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/mm_request_jobs/show.html.erb
<h5>MeatMarket : Job Details</h5>
<div class="panel panel-primary">
  <div class="panel-primary">
    <div class="panel-heading"> ID: <%= @import.import_id %> - <%= @import.job_name.gsub('_', ' ') %></div>
  </div>
  <div class="panel-body">
    <table id="table_starting_fifteen" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
      <thead>
      <tr>
        <th class="text-center" >#</th>
        <th class="text-center" >Advert ID:</th>
        <th class="text-center" >Description</th>
        <th class="text-center" >From</th>
        <th class="text-center" >To</th>
        <th class="text-center" >Halaal/Kosher</th>
        <th class="text-center" >PB Avail</th>
        <th class="text-center" >Request Processed</th>
        <th class="text-center" >SPM Code</th>
      </tr>
      </thead>
      <tbody>
      <% count = 0 %>
      <% error_count = 0 %>
      <% @adverts.each do |advert| %>
          <tr class="<%= row_state(advert) %>">
            <td class="text-center"  ><%=  count += 1 %></td>
            <td class="text-center"  ><%=  advert.id %></td>
            <td class="text"><%= advert.description %></td>
            <td class="text-center"><%= advert.start_date %></td>
            <td class="text-center"><%= advert.end_date %></td>
            <td class="text-center"> <i class="fa fa-<%= status_halaal(advert) %> fa-2x" aria-hidden="true"></i></td>
            <td class="text-center"> <i class="fa fa-<%= pb_available(advert ) %> fa-2x" aria-hidden="true"></i></td>
            <td class="text-center"> <i class="fa fa-<%= request_processed(advert ) %> fa-2x" aria-hidden="true"></i></td>
            <td class="text"><%= advert.spm_code %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <tbody>
      <tr>
        <td class="text-center"><%= button_to "Back", :back, method: :get, class: "btn btn-success btn-sm"  %></td>
        <td class="text-center"><%= button_to "Request Jobs", mm_request_jobs_path, method: :get, class: "btn btn-success btn-sm"  %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
<i class="icon-github"></i>