config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # get 'mm_request/index'
  #
  # get 'mm_request/show'
  #
  # get 'mm_process_excel_import/index'
  #
  # get 'mm_process_excel_import/show'
  #
  # get 'long_services/index'
  #
  # get 'long_services/jobs'
  #
  # get 'long_services/assets'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  #
  # get 'generators/index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'mm_assets/pb_bodies'

  get 'mm_assets/music'

  get 'mm_assets/price_vals'

  get 'mm_assets/index'

  get 'mm_assets/show'

  get 'mm_assets/required'

  #
  get 'mm_reports/halaal_stores'

  get 'mm_reports/non_halaal_products'


  resources :berta, only: [:index] do
    get :index, on: :member
  end


get 'imports/destroy_all'
  resources :imports, only: [:index, :new, :create, :destroy] do
    put :process_zip_file, on: :member
    put :process_mp3_file, on: :member
    # get :destroy_all, on: :member
  end

  # get 'mm_requests/new_requests'

  resources :mm_adverts

  resources :mm_requests

  get 'mm_request_jobs/download_job'

  resources :mm_request_jobs

  resources :ls_requests

  root 'berta#index'

end

app/models/import.rb
# frozen_string_literal: true
class Import < ActiveRecord::Base
  mount_uploader :imported_file, ImportedFileUploader # Tells rails to use this uploader for this model.
  # validates :name, presence: true # Make sure the owner's name is present.
end

app/controllers/imports_controller.rb
# frozen_string_literal: true
class ImportsController < ApplicationController
  include ExcelsHelper
  include CleanupHelper

  def index
    @imports = Import.all
  end

  def process_zip_file
    import      = Import.find(params[:id])
    file        = import.imported_file.file.file
    id          = import.id
    @file_name  = File.basename(file)
    ImporterJob.perform_now(file, id)
    @imports = Import.all
    redirect_to imports_path, notice: "The import #{import.imported_file.filename} has been processed."
  end

  def new
    @import = Import.new
  end

  def create
    @import = Import.new(import_params)
    @import.user_id = current_user.id
    @import.processable = true
    if @import.save
      redirect_to imports_path, notice: "The import #{@import.imported_file.filename} has been uploaded."
    else
      render 'new'
    end
  end

  def destroy
    @import = Import.find(params[:id])
    @import.destroy
    @requests = MmRequest.where(import_id: @import.id)
    @requests.destroy_all
    @adverts = MmAdvert.where(import_id: @import.id)
    @adverts.destroy_all
    @job_requests = MmRequestJob.where(import_id: @import.id).destroy_all
    redirect_to imports_path, notice: "The import #{@import.imported_file.filename} has been deleted."
  end

  def destroy_all
    clear_all_imports
    redirect_to imports_path, notice: 'ALL DESTROYED'
  end

  private

  def import_params
    params.require(:import).permit(:imported_file, :user_id)
  end
end

app/helpers/imports_helper.rb
# frozen_string_literal: true
module ImportsHelper
  def process_by_type(import)
    return content_tag(:span, 'Processed') if processed_state(import)
    return content_tag(:span, 'Unprocessable') unless import.processable

    return button_to('Request Job Ready',
                     mm_request_jobs_path,
                     method: :post,
                     class: 'btn btn-success btn-xs',
                     data: { disable_with: "Processing. Please wait..." }) if job_state(import)

    type = File.extname(import.imported_file.file.file)
    return button_to('Process XLS',
                     mm_requests_path(import.id),
                     params: { id: import.id },
                     method: :post,
                     class: 'btn btn-warning btn-xs',
                     data: { disable_with: "Processing. Please wait..." })  if type == '.xls' || type == '.xlsx'

    return button_to('Process Zip',
                     process_zip_file_import_path(import),
                     method: :put,
                     class: 'btn btn-warning btn-xs',
                     data: { disable_with: "Processing. Please wait..." })  if type == '.zip'
  end

  def import_row_color(import)
    if import.request_job.eql?(true)
      return 'warning' if import.note.nil?
      return 'warning' if import.note.empty?
      return 'success' if import.note.include?('Job completed')
    else
      return 'info' if import.processed.eql?(true)
    end
    'warning'
  end

  def trash_or_locked(import)
    return fa_icon "lock 2x" if import.processed.eql?(true)
    link_to '<i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>'.html_safe, import_path(import.id), method: :delete
  end

  def date_format(time)
    time.localtime.strftime('%d-%m-%y %H:%M')
  end
end

app/views/imports/_form.html.erb
<%= simple_form_for @import, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.input :name %>
    <%= f.input :import_file %>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  import_path, :class => 'btn' %>
    </div>
<% end %>

app/views/imports/_process_excel_file.html.erb
<!--<h4>Import Specials - Moved to mm_request/show</h4>-->
<!--<div class="panel panel-primary">-->
<!--<div class="panel-heading">-->
<!--<h3 class="panel-title">Processing: <%= @file_name %></h3>-->
<!--</div>-->
<!--<div class="panel-body">-->
<!--Please check the import and use the options at the bottom of this page.-->
<!--<div class="table-responsive">-->
<!--<table class="table table-striped table-bordered  table-hover " style="font-size:10px;">-->
<!--<thead>-->
<!--<tr>-->
<!--<th class="text-center" >#</th>-->
<!--<th class="text-center" >Item Code</th>-->
<!--<th class="text-center" >Item Description</th>-->
<!--<th class="text-center" >Brand</th>-->
<!--<th class="text-center" >Region</th>-->
<!--<th class="text-center" >Store Code</th>-->
<!--<th class="text-center" >Store Name</th>-->
<!--<th class="text-center" >From</th>-->
<!--<th class="text-center" >To</th>-->
<!--<th class="text-center" >Price</th>-->
<!--<th class="text-center" >Unit</th>-->
<!--<th class="text-center" >Extra</th>-->
<!--<th class="text-center" >MSG</th>-->
<!--</tr>-->
<!--</thead>-->
<!--<tbody>-->
<!--<% count = 0 %>-->
<!--<% error_count = 0 %>-->
<!--<% @requests.each do |request| %>-->
    <!--<tr class="<%= row_state(request.request_ok) %>">-->
    <!--<td class="text-center"  ><%=  count += 1 %></td>-->
    <!--<td class="text-center"><%= request.item_code %></td>-->
    <!--<td class="col-md-2"><%= request.item_descr %></td>-->
    <!--<td > <%= request.brand_short %></td>-->
    <!--<td class="col-md-2 <%= status_region(request.region_short)%>"> <%= clean_array(request.region_short) %></td>-->
    <!--<td > <%= request.store_code %></td>-->
    <!--<td > <%= request.store_name %></td>-->
    <!--<td class="text-center"><%= request.from.strftime("%d-%b-%Y") %></td>-->
    <!--<td class="text-center"><%= request.to.strftime("%d-%b-%Y")  %></td>-->
    <!--<td class="text-center"><%= number_to_currency(request.price, :unit => "") %></td>-->
    <!--<td class="text-center"><%= request.unit %></td>-->
    <!--<td class="text-center"><%= request.extra_1 %></td>-->
    <!--<td class="text-center"><%= button_type(request.request_ok) %></td>-->
    <!--</tr>-->
    <!--<% error_count += 1 unless request.request_ok %>-->
    <!--<% end %>-->
<!--</tbody>-->
<!--</table>-->
<!--</div>-->
<!--<div class="table-responsive">-->
<!--<table class="table table-bordered table-striped">-->
<!--<tbody>-->
Total Rows: <%= count %>
Failures:  <%= error_count %>
<!--</tr>-->
<!--</tbody>-->
<!--</table>-->
<!--</div>-->
<!--</div>-->
<!--<div class="table-responsive">-->
<!--<table class="table table-bordered table-striped">-->
<!--<tbody>-->
<!--<td class="text-center"><%= button_to "Cancel",  root_path, method: :get, class: "btn btn-danger"  %></td>-->
<!--<% unless error_count > 0 %>-->
    <!--<td class="text-center"><%= button_to "Create Job", mm_advert_path(id: @requests.first.import_id), method: :put, class: "btn btn-success"  %></td>-->
    <!--<% end %>-->
<!--</tr>-->
<!--</tbody>-->
<!--</table>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--<br>-->
<!--<br>-->
<!--<br>-->
<!--<br>-->

app/views/imports/_process_excel_file_view.html.erb
<h4>Import Specials</h4>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Processing: <%= @file_name %></h3>
  </div>
  <div class="panel-body">
    Please check the import and use the options at the bottom of this page.
    <div class="table-responsive">
      <table id="table_starting_fifteen" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
        <thead>
          <tr>
            <th class="text-center" >#</th>
            <th class="text-center" >Item Code</th>
            <th class="text-center" >Item Description</th>
            <th class="text-center" >Brand</th>
            <th class="text-center" >Region</th>
            <th class="text-center" >Store Code</th>
            <th class="text-center" >Store Name</th>
            <th class="text-center" >From</th>
            <th class="text-center" >To</th>
            <th class="text-center" >Price</th>
            <th class="text-center" >Unit</th>
            <th class="text-center" >Extra</th>
            <th class="text-center" >MSG</th>
          </tr>
        </thead>
        <tbody>
          <% count = 0 %>
          <% error_count = 0 %>
          <% @requests.each do |request| %>
            <tr class="<%= row_state(request.request_ok) %>">
              <td class="text-center"  ><%=  count += 1 %></td>
              <td class="text-center"><%= request.item_code %></td>
              <td class="col-md-2"><%= request.item_descr %></td>
              <td > <%= request.brand_short %></td>
              <td class="col-md-2 <%= status_region(request.region_short)%>"> <%= clean_array(request.region_short) %></td>
              <td > <%= request.store_code %></td>
              <td > <%= request.store_name %></td>
              <td class="text-center"><%= request.from.strftime("%d-%b-%Y") %></td>
              <td class="text-center"><%= request.to.strftime("%d-%b-%Y")  %></td>
              <td class="text-center"><%= number_to_currency(request.price, :unit => "") %></td>
              <td class="text-center"><%= request.unit %></td>
              <td class="text-center"><%= request.extra_1 %></td>
              <td class="text-center"><%= button_type(request.request_ok) %></td>
            </tr>
            <% error_count += 1 unless request.request_ok %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <tbody>
          Total Rows: <%= count %>
          Failures:  <%= error_count %>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <tbody>
      <td class="text-center"><%= button_to "Cancel",  root_path, method: :get, class: "btn btn-danger"  %></td>
      <% unless error_count > 0 %>
        <td class="text-center"><%= button_to "Create Job", mm_advert_path(id: @requests.first.import_id), method: :put, class: "btn btn-success"  %></td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>

app/views/imports/_process_zip_file.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h4 class="panel-title">Processing: <%= @file_name %></h4>
  </div>
  <div class="panel-body">
    Please check the import and use the options at the bottom of this page.
    <div class="table-responsive">
      <table id="table_starting_fifteen" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
        <thead>
          <tr>
            <th class="text-center" >#</th>
            <th class="text-center" >Item Code</th>
            <th class="text-center" >Item Description</th>
            <th class="text-center" >Brand</th>
            <th class="text-center" >Region</th>
            <th class="text-center" >From</th>
            <th class="text-center" >To</th>
            <th class="text-center" >Price</th>
            <th class="text-center" >Unit</th>
            <th class="text-center" >Extra</th>
            <th class="text-center" >Extra</th>
            <th class="text-center" >MSG</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <tbody>
          <% @imported.each do |import| %>
            <%= import.inspect %> <br>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/imports/index.html.erb
<h4>Import</h4>
<br/>
<%= link_to "New Import", new_import_path, class: "btn btn-info btn-xs" %>
<br />
<br />
<table id="table_starting_fifteen" class="table table-bordered table-striped">
  <thead>
  <tr>
    <th class="text-center">Import#</th>
    <th class="text-center">Date</th>
    <th class="text-center">Description</th>
    <th class="text-center">Uploader</th>
    <th class="text-center">Process</th>
    <th class="text-center">Note</th>
    <th class="text-center">Trash</th>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @imports.sort.reverse.each do |import| %>
      <% next if import.imported_file.file.nil? %>
      <tr class="<%= import_row_color(import) %>">
        <td class="text-center"><%= import.id %></td>
        <td ><%= date_format(import.created_at) %></td>
        <td ><%= File.basename(import.imported_file.file.file) %></td>
        <td ><%= User.where(id: import.user_id)[0].email %></td>
        <td class="text-center"><%= process_by_type(import) %></td>
        <td class="text-center"><%= import.note %></td>
        <td class="text-center"><%= trash_or_locked(import) %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br />
<br />
<br />
<br />
<br />
<br />
<%= link_to "Destroy All", imports_destroy_all_path(@imports), class: "btn btn-alert" %>
<br />

app/views/imports/new.html.erb
<h4>Imports</h4>
<% if !@import.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="well">
  <%= simple_form_for @import, html: { multipart: true } do |f| %>
    <%= f.label :imported_file %>
    <%= f.file_field :imported_file %><br>
    <%= f.submit "Save", class: "btn btn-primary btn-sm", data: { disable_with: "Uploading. Please wait..." } %>
  <% end %>
</div>