config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # get 'mm_request/index'
  #
  # get 'mm_request/show'
  #
  # get 'mm_process_excel_import/index'
  #
  # get 'mm_process_excel_import/show'
  #
  # get 'long_services/index'
  #
  # get 'long_services/jobs'
  #
  # get 'long_services/assets'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  #
  # get 'generators/index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'mm_assets/pb_bodies'

  get 'mm_assets/music'

  get 'mm_assets/price_vals'

  get 'mm_assets/index'

  get 'mm_assets/show'

  get 'mm_assets/required'

  #
  get 'mm_reports/halaal_stores'

  get 'mm_reports/non_halaal_products'


  resources :berta, only: [:index] do
    get :index, on: :member
  end


get 'imports/destroy_all'
  resources :imports, only: [:index, :new, :create, :destroy] do
    put :process_zip_file, on: :member
    put :process_mp3_file, on: :member
    # get :destroy_all, on: :member
  end

  # get 'mm_requests/new_requests'

  resources :mm_adverts

  resources :mm_requests

  get 'mm_request_jobs/download_job'

  resources :mm_request_jobs

  resources :ls_requests

  root 'berta#index'

end

app/models/mm_request.rb
# frozen_string_literal: true
class MmRequest < ActiveRecord::Base
end

app/controllers/mm_requests_controller.rb
class MmRequestsController < ApplicationController
  def index
    @requests = Import.where(id: MmRequest.distinct.pluck(:import_id))
  end
  def create
    import = Import.find(params[:id])
    file = import.imported_file.file.file
    id = import.id

    job_name = Import.where(id: params[:id])[0].imported_file.file.file.split('/').last.gsub('.xlsx', '').gsub('.xls', '').gsub('Copy_of_', '')

    MmRequestJob.where(import_id: params[:id]).first_or_create(import_id: params[:id], job_name: job_name)

    MmRequestValidator.new(file, id)
    import = Import.find(params[:id])

    if import.processable
      MmProcessRequests.new(file, id)
      @file_name = File.basename(file)
      @requests = MmRequest.where(import_id: id)
      @import = MmRequestJob.where(import_id: params[:id]).last
      import.request_job = true
      import.save
      render 'show'
    else
      redirect_to imports_path, alert: "There are issues with the request sheet. #{import.note}"
    end
  end

  def show
    @requests = MmRequest.where(import_id: params[:id])
    @import = MmRequestJob.where(import_id: params[:id]).last
  end
end

app/helpers/mm_requests_helper.rb
module MmRequestsHelper

  def request_title(request)
   request[:imported_file].delete('.xlsx').delete('.xls')
  end




end

app/views/mm_requests/index.html.erb
<h4>MeatMarket Requests</h4>
<p> Still need to sort this out</p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Processing: <%= @file_name %></h3>
  </div>
  <div class="panel-body">
    Please check the import and use the options at the bottom of this page.
    <div class="table-responsive">
      <table id="table_starting_ten" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
        <thead>
        <tr>
          <th class="text-center" >#</th>
          <th class="text-center" >Import ID</th>
          <th class="text-center" >Request Name</th>
          <th class="text-center" >View Request</th>
        </tr>
        </thead>
        <tbody>
        <% count = 0 %>
        <% @requests.each do |request| %>
            <tr>
              <td class="text-center"  ><%= count += 1 %></td>
              <td class="text-center"><%= request.id %></td>
              <td class="col-md-2"><%= request_title(request) %></td>
              <td class="text-center"><%=link_to('View', {:controller => :mm_requests, :action => 'show', :id => request.id}, class: 'btn btn-primary btn-xs')  %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/mm_requests/show.html.erb
<h5>MeatMarket : Request Details</h5>
<div class="panel panel-primary">
  <div class="panel-primary">
    <div class="panel-heading"> ID: <%= @import.import_id %> - <%= @import.job_name.gsub('_', ' ') %></div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table id="table_starting_ten" class="table table-striped table-bordered  table-hover " style="font-size:10px;">
        <thead>
        <tr>
          <th class="text-center" >#</th>
          <th class="text-center" >Import ID</th>
          <th class="text-center" >Item Code</th>
          <th class="text-center" >Item Description</th>
          <th class="text-center" >Brand</th>
          <th class="text-center" >Region</th>
          <th class="text-center" >Store Code</th>
          <th class="text-center" >Store Name</th>
          <th class="text-center" >From</th>
          <th class="text-center" >To</th>
          <th class="text-center" >Price</th>
          <th class="text-center" >Unit</th>
          <th class="text-center" >Extra</th>
          <th class="text-center" >MSG</th>
        </tr>
        </thead>
        <tbody>
        <% count = 0 %>
        <% @error_count = 0 %>
        <% @requests.each do |request| %>
            <tr class="<%= row_state(request.request_ok) %>">
              <td class="text-center"  ><%=  count += 1 %></td>
              <td class="text-center"><%= request.import_id %></td>
              <td class="text-center"><%= request.item_code %></td>
              <td class="col-md-2"><%= request.item_descr %></td>
              <td > <%= request.brand_short %></td>
              <td class="col-md-2 <%= status_region(request.region_short)%>"> <%= clean_array(request.region_short) %></td>
              <td > <%= request.store_code %></td>
              <td > <%= request.store_name %></td>
              <td class="text-center"><%= request.from.strftime("%d-%b-%Y") %></td>
              <td class="text-center"><%= request.to.strftime("%d-%b-%Y")  %></td>
              <td class="text-center"><%= number_to_currency(request.price, :unit => "") %></td>
              <td class="text-center"><%= request.unit %></td>
              <td class="text-center"><%= request.extra_1 %></td>
              <td class="text-center"><%= button_type(request.request_ok) %></td>
            </tr>
            <% @error_count += 1 unless request.request_ok %>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <tbody>
        Total Rows: <%= count %>
        Failures:  <%= @error_count %>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <% unless MmRequestJob.where(import_id: @requests.first.import_id)[0][:request_accepted] && MmRequestJob.where(import_id: @requests.first.import_id)[0][:advert_requests_accepted] %>
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <tbody>
          <tr>
            <td class="text-center"><%= button_to "Cancel", :back, method: :get, class: "btn btn-danger"  %></td>
            <% unless @error_count > 0 %>
                <%  MmRequestJob.where(import_id: @requests.first.import_id).update(request_accepted: true) %>
                <td class="text-center"><%= button_to "Accept Requests", mm_adverts_path(id: @requests.first.import_id), method: :post, class: "btn btn-success", data: { disable_with: "Processing. Please wait..." } %></td>
            <% end %>
          </tr>
          </tbody>
        </table>
      </div>
  <% else %>
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <tbody>
          <tr>
            <td class="text-center"><%= button_to "Back", :back, method: :get, class: "btn btn-success btn-sm"  %></td>
            <td class="text-center"><%= button_to "View Adverts", mm_advert_path, method: :get, class: "btn btn-success btn-sm"  %></td>
            <td class="text-center"><%= button_to "Request Jobs", mm_request_jobs_path, method: :get, class: "btn btn-success btn-sm"  %></td>
          </tr>
          </tbody>
        </table>
      </div>
  <% end %>
</div>